// Starter content library — a curated, high-quality cross-pillar set.
// Quality over volume: every activity has a clear purpose, measurable success
// where relevant, common mistakes, and easier/harder variations.
//
// Skill drills reuse the existing brand artwork; fitness/recovery activities
// render a category glyph tile (no thumbnail) until real media is added.

import { ImageSourcePropType } from 'react-native';
import { Activity } from './schema';

const IMG = {
  chip: require('../../assets/drills/drill-chip.webp') as ImageSourcePropType,
  putt: require('../../assets/drills/drill-putt.webp') as ImageSourcePropType,
  tempo: require('../../assets/drills/drill-tempo.webp') as ImageSourcePropType,
  drive: require('../../assets/drills/drill-drive.webp') as ImageSourcePropType,
  irons: require('../../assets/drills/drill-irons.webp') as ImageSourcePropType,
  setup: require('../../assets/drills/drill-setup.webp') as ImageSourcePropType,
};

const DATE = '2026-07-14';

// Factory: fills the CMS-boilerplate fields so each entry stays focused on
// meaningful content. Author/dates/premium default here; override as needed.
function mk(a: Omit<Activity, 'premium' | 'author' | 'createdAt' | 'updatedAt'> & Partial<Pick<Activity, 'premium' | 'author' | 'createdAt' | 'updatedAt'>>): Activity {
  return {
    premium: false,
    author: 'GolfHaus Coaching',
    createdAt: DATE,
    updatedAt: DATE,
    ...a,
  };
}

// ─── Golf skill drills (migrated from the original library) ─────────────────

const skillDrills: Activity[] = [
  mk({
    id: 'ladder', title: 'Landing Spot Ladder', summary: 'Land chips on a chosen spot and let the ball release.',
    type: 'drill', category: 'Chipping', subcategory: 'Landing control', goals: ['chipping', 'break100', 'striking'],
    problem: 'Chips that fly the wrong distance and finish far from the hole.',
    skillLevel: 'beginner', physDifficulty: 1, locations: ['range', 'course', 'outdoor'],
    equipmentRequired: ['clubs', 'balls'], durationMin: 12,
    setup: 'Drop 10 balls just off the edge of the green.',
    steps: [
      'Pick a clear landing spot — a leaf, a towel, an old divot.',
      'Make relaxed, equal-length swings and let the loft lift it.',
      'Land it on your spot. Don’t chase the hole — trust the roll.',
    ],
    cues: ['Weight slightly forward, stays there', 'Quiet hands — rock the shoulders', 'Same easy tempo every chip'],
    feel: 'A putting-like rock of the shoulders, hands staying passive.',
    mistakes: ['Flicking with the wrists', 'Aiming at the hole instead of the landing spot'],
    easier: 'Use a bigger landing zone and a single club.', harder: 'Shrink the zone and change spots every ball.',
    bodyAreas: ['shoulders', 'core'], golfSkills: ['chipping'], thumbnail: IMG.chip,
    scoring: { unit: 'of 10', target: 7, better: 'higher', prompt: 'How many finished close?' },
    tags: ['short game', 'scoring'], frequency: '2–3× per week',
  }),
  mk({
    id: 'clock', title: 'The Clock Drill', summary: 'Dial in lag-putt pace so the first putt cosies up close.',
    type: 'drill', category: 'Putting', subcategory: 'Distance control', goals: ['putting', 'break100', 'break90'],
    problem: 'Three-putts caused by poor speed, not line.',
    skillLevel: 'beginner', physDifficulty: 1, locations: ['green', 'home'],
    equipmentRequired: ['clubs', 'balls'], equipmentOptional: ['puttingMat'], durationMin: 10,
    setup: 'Place balls at 3, 6 and 9 feet around one hole.',
    steps: ['Putt the closest ring first, then work outward.', 'Watch the pace, not the line — aim to die it at the hole.', 'Any putt that finishes past the hole, start the ring again.'],
    cues: ['Eyes over the ball at setup', 'Smooth back, smooth through', 'Let the putter do the work'],
    feel: 'An even, unhurried stroke with no hit at the ball.',
    mistakes: ['Decelerating into short putts', 'Steering the line and forgetting speed'],
    easier: 'Use one distance and a putter-length target circle.', harder: 'Add a 12-foot ring and finish with a pressure putt.',
    bodyAreas: ['shoulders'], golfSkills: ['putting'], thumbnail: IMG.putt,
    scoring: { unit: 'of 10', target: 8, better: 'higher', prompt: 'How many lag putts stopped close?' },
    tags: ['putting', 'scoring'], frequency: '2–3× per week',
  }),
  mk({
    id: 'tempo', title: 'One-Hand Tempo', summary: 'Build repeatable swing rhythm at home, no ball needed.',
    type: 'drill', category: 'Setup & Tempo', subcategory: 'Fundamentals', goals: ['striking', 'generalFitness', 'confidence'],
    problem: 'An inconsistent, jerky swing tempo under pressure.',
    skillLevel: 'beginner', physDifficulty: 1, locations: ['home', 'hotel', 'outdoor'],
    equipmentRequired: ['clubs'], durationMin: 6,
    setup: 'Grip a mid-iron with your lead hand only, near the bottom.',
    steps: ['Make slow half-swings, feeling the club’s weight swing through.', 'Count “one-two” back, “three” through — same every time.', 'Add your other hand back on, keep the exact same rhythm.'],
    cues: ['Loose grip pressure', 'Let it swing, don’t force it', 'Balanced finish, hold it'],
    feel: 'The clubhead swinging you, not you muscling the club.',
    mistakes: ['Gripping too tight', 'Rushing the transition'],
    easier: 'Half-swings only, feet together.', harder: 'Full one-handed swings, then alternate hands.',
    bodyAreas: ['core', 'shoulders', 'wrists'], golfSkills: ['full swing', 'tempo'], thumbnail: IMG.tempo,
    tags: ['home', 'tempo'], frequency: 'Daily is fine',
  }),
  mk({
    id: 'gate', title: 'Gate Putting', summary: 'Roll putts through a tee gate to square the face at impact.',
    type: 'drill', category: 'Putting', subcategory: 'Start line', goals: ['putting', 'straighter'],
    problem: 'Putts that start off line even with good speed.',
    skillLevel: 'beginner', physDifficulty: 1, locations: ['green', 'home'],
    equipmentRequired: ['clubs', 'balls'], equipmentOptional: ['puttingMat'], durationMin: 8,
    setup: 'Stick two tees a ball-and-a-bit apart, just ahead of the ball.',
    steps: ['Aim at a hole 6–8 feet away.', 'Roll putts through the gate without clipping either tee.', 'Clip one? Note which side and reset.'],
    cues: ['Eyes directly over the ball', 'Putter face square at the gate', 'Smooth, unhurried stroke'],
    feel: 'The face staying square through a short, quiet stroke.',
    mistakes: ['Peeking at the hole early', 'Manipulating the face with the hands'],
    easier: 'Widen the gate and shorten the putt.', harder: 'Narrow the gate to barely wider than the ball.',
    bodyAreas: ['shoulders'], golfSkills: ['putting'], thumbnail: IMG.putt,
    scoring: { unit: 'of 10', target: 8, better: 'higher', prompt: 'How many rolled through clean?' },
    tags: ['putting'], frequency: '2× per week',
  }),
  mk({
    id: 'bump', title: 'Bump & Run Bowls', summary: 'Trainer the low-running chip that gets you out of trouble.',
    type: 'drill', category: 'Chipping', subcategory: 'Bump and run', goals: ['chipping', 'break90'],
    problem: 'Over-flying simple greenside chips.',
    skillLevel: 'intermediate', physDifficulty: 1, locations: ['course', 'range', 'outdoor'],
    equipmentRequired: ['clubs', 'balls'], durationMin: 12,
    setup: 'Use an 8 or 9-iron, ball back in your stance.',
    steps: ['Pick a landing spot a few feet onto the green.', 'Make a putting-style stroke — minimal wrist.', 'Watch it release and roll toward the hole.'],
    cues: ['Hands ahead of the ball', 'Low follow-through', 'Trust the roll'],
    feel: 'A firm-wristed putt that happens to get airborne briefly.',
    mistakes: ['Trying to lift the ball', 'Too much wrist hinge'],
    easier: 'One club, one target.', harder: 'Vary clubs and landing spots each ball.',
    bodyAreas: ['shoulders', 'core'], golfSkills: ['chipping'], thumbnail: IMG.chip,
    scoring: { unit: 'of 10', target: 6, better: 'higher', prompt: 'How many finished in the zone?' },
    tags: ['short game'], frequency: '1–2× per week',
  }),
  mk({
    id: 'tee', title: 'Tee Height Ladder', summary: 'Find the centre of the driver face by laddering tee heights.',
    type: 'drill', category: 'Driving', subcategory: 'Strike', goals: ['driverConsistency', 'distance', 'striking'],
    problem: 'Off-centre driver strikes that lose distance and direction.',
    skillLevel: 'intermediate', physDifficulty: 2, locations: ['range'],
    equipmentRequired: ['clubs', 'balls'], durationMin: 14,
    setup: 'Tee the ball low for the first 5 swings.',
    steps: ['Tee it standard height for the next 5.', 'Feel where the face meets the ball each time.', 'Settle on the height that finds the middle most.'],
    cues: ['Tilt slightly behind the ball', 'Sweep up through impact', 'Stay balanced to the finish'],
    feel: 'A flush, effortless-feeling strike off the centre.',
    mistakes: ['Swinging harder for distance', 'Sliding ahead of the ball'],
    easier: 'Hit off a tee at one comfortable height.', harder: 'Score each strike location with face spray.',
    bodyAreas: ['core', 'legs'], golfSkills: ['driving'], thumbnail: IMG.drive,
    scoring: { unit: 'of 10', target: 6, better: 'higher', prompt: 'How many found the middle?' },
    tags: ['driving'], frequency: '1× per week',
  }),
  mk({
    id: 'towel', title: 'Towel Under Arms', summary: 'Keep arms and body connected for crisp iron contact.',
    type: 'drill', category: 'Iron play', subcategory: 'Connection', goals: ['ironContact', 'striking'],
    problem: 'Thin and fat irons from arms disconnecting from the body.',
    skillLevel: 'beginner', physDifficulty: 2, locations: ['range', 'home', 'outdoor'],
    equipmentRequired: ['clubs'], equipmentOptional: ['balls'], durationMin: 7,
    setup: 'Tuck a towel under both upper arms.',
    steps: ['Make half-swings keeping the towel in place.', 'If it drops, your arms disconnected — reset.', 'Build up to fuller swings, towel still held.'],
    cues: ['Chest and arms turn together', 'No flailing at the top', 'Rotate through, towel stays put'],
    feel: 'The chest and arms moving as one connected unit.',
    mistakes: ['Lifting the arms independently', 'Stopping the body rotation'],
    easier: 'Slow half-swings, no ball.', harder: 'Full swings hitting balls, towel held.',
    bodyAreas: ['core', 'upperBack', 'shoulders'], golfSkills: ['iron play'], thumbnail: IMG.irons,
    tags: ['irons', 'contact'], frequency: '2× per week',
  }),
  mk({
    id: 'align', title: 'Alignment Stick Setup', summary: 'Rewire your eyes to what "straight" really looks like.',
    type: 'drill', category: 'Setup & Tempo', subcategory: 'Aim', goals: ['straighter', 'confidence'],
    problem: 'Aiming off-target without realising it.',
    skillLevel: 'beginner', physDifficulty: 1, locations: ['home', 'range', 'outdoor'],
    equipmentRequired: ['alignmentSticks'], equipmentOptional: ['clubs'], durationMin: 5,
    setup: 'Lay one stick along your toe line.',
    steps: ['Lay a second pointing at your target.', 'Build your stance parallel to the sticks.', 'Step away, step back, rebuild it from scratch.'],
    cues: ['Feet, hips, shoulders all parallel', 'Aim the clubface first', 'Body lines follow the club'],
    feel: 'Your body lines running parallel-left of the target line.',
    mistakes: ['Aiming the body at the target instead of parallel', 'Setting feet before the clubface'],
    easier: 'Just the target-line stick.', harder: 'Rebuild with eyes closed, then check.',
    bodyAreas: ['fullBody'], golfSkills: ['setup', 'alignment'], thumbnail: IMG.setup,
    scoring: { unit: 'of 10', target: 8, better: 'higher', prompt: 'How many setups felt square?' },
    tags: ['setup', 'no ball'], frequency: 'Before every range session',
  }),
  mk({
    id: 'coin', title: 'Coin Toss Lag', summary: 'Putt to a coin to feel pace instead of steering line.',
    type: 'drill', category: 'Putting', subcategory: 'Distance control', goals: ['putting', 'break90'],
    problem: 'Poor speed control on long putts.',
    skillLevel: 'intermediate', physDifficulty: 1, locations: ['green'],
    equipmentRequired: ['clubs', 'balls'], durationMin: 9,
    setup: 'Place a coin 25–35 feet away — no hole needed.',
    steps: ['Putt to stop the ball directly over the coin.', 'Reset the coin a different distance each time.', 'Score a point for anything within a foot.'],
    cues: ['Look at the coin, not the ball', 'Longer stroke, same tempo', 'Let it die at the target'],
    feel: 'Length of stroke — not effort — controlling distance.',
    mistakes: ['Adding a hit for longer putts', 'Fixed stroke length regardless of distance'],
    easier: 'One fixed distance.', harder: 'Random distances called by a partner.',
    bodyAreas: ['shoulders'], golfSkills: ['putting'], thumbnail: IMG.putt,
    scoring: { unit: 'of 10', target: 7, better: 'higher', prompt: 'How many stopped over the coin?' },
    tags: ['putting'], frequency: '1–2× per week',
  }),
  mk({
    id: 'flop', title: 'High Soft Flop', summary: 'Build confidence to hit a high, soft-landing greenside shot.',
    type: 'drill', category: 'Pitching', subcategory: 'Trajectory', goals: ['chipping', 'confidence'],
    problem: 'No escape when short-sided with little green to work with.',
    skillLevel: 'advanced', physDifficulty: 2, locations: ['course', 'range', 'outdoor'],
    equipmentRequired: ['clubs', 'balls'], durationMin: 11,
    setup: 'Open your stance and the clubface wide.',
    steps: ['Play the ball forward, weight slightly left.', 'Make a long, unhurried swing — accelerate through.', 'Let the loft pop it up and land it soft.'],
    cues: ['Commit — never decelerate', 'Keep the face open through impact', 'Full finish, high hands'],
    feel: 'The clubhead sliding under the ball with speed.',
    mistakes: ['Decelerating from fear', 'Closing the face through impact'],
    safety: 'Practise off good lies first — thin shots can travel fast.',
    easier: 'Half flop with less face open.', harder: 'Short-sided over a bunker to a tight pin.',
    bodyAreas: ['core', 'shoulders'], golfSkills: ['pitching'], thumbnail: IMG.chip,
    scoring: { unit: 'of 10', target: 5, better: 'higher', prompt: 'How many landed soft?' },
    tags: ['short game', 'advanced'], frequency: '1× per week',
  }),
  mk({
    id: 'bunker', title: 'Line in the Sand', summary: 'Groove a consistent sand-entry point for reliable escapes.',
    type: 'drill', category: 'Bunker play', subcategory: 'Entry point', goals: ['bunker', 'confidence'],
    problem: 'Inconsistent bunker contact — hitting the ball, not the sand.',
    skillLevel: 'intermediate', physDifficulty: 2, locations: ['course', 'range'],
    equipmentRequired: ['clubs'], equipmentOptional: ['balls'], durationMin: 10,
    setup: 'Draw a line in the sand, no ball yet.',
    steps: ['Splash sand starting right on the line.', 'Repeat until your entry point is consistent.', 'Add a ball just ahead of the line and swing the same.'],
    cues: ['Hit the sand, not the ball', 'Open face, use the bounce', 'Keep swinging through the sand'],
    feel: 'The club splashing a consistent divot of sand.',
    mistakes: ['Digging steeply', 'Quitting on the shot'],
    easier: 'Entry practice only, no ball.', harder: 'Vary distances by swing length.',
    bodyAreas: ['core', 'shoulders'], golfSkills: ['bunker'], thumbnail: IMG.irons,
    scoring: { unit: 'of 10', target: 7, better: 'higher', prompt: 'How many escaped first try?' },
    tags: ['bunker'], frequency: '1× per week',
  }),
  mk({
    id: 'punch', title: 'Knock-Down Punch', summary: 'Own a lower, controlled iron flight for wind and tight holes.',
    type: 'drill', category: 'Iron play', subcategory: 'Trajectory', goals: ['ironContact', 'courseMgmt', 'striking'],
    problem: 'Only owning one trajectory, wrecked by wind.',
    skillLevel: 'intermediate', physDifficulty: 2, locations: ['range'],
    equipmentRequired: ['clubs', 'balls'], durationMin: 9,
    setup: 'Take one more club than normal, grip down.',
    steps: ['Play the ball an inch back in your stance.', 'Make a smooth ¾ backswing.', 'Finish low — hands stop around chest height.'],
    cues: ['Quiet, controlled tempo', 'Shorter follow-through', 'Cover the ball, hands ahead'],
    feel: 'A compact, three-quarter swing with a low finish.',
    mistakes: ['Swinging full and fast', 'Hanging back to help it up'],
    easier: 'Half swings to a soft target.', harder: 'Flight three heights with one club.',
    bodyAreas: ['core'], golfSkills: ['iron play'], thumbnail: IMG.drive,
    scoring: { unit: 'of 10', target: 6, better: 'higher', prompt: 'How many flew low and straight?' },
    tags: ['irons', 'trajectory'], frequency: '1× per week',
  }),
  mk({
    id: 'mirror', title: 'Mirror Posture Check', summary: 'Train an athletic, balanced setup you can’t feel on your own.',
    type: 'drill', category: 'Setup & Tempo', subcategory: 'Posture', goals: ['striking', 'confidence', 'generalFitness'],
    problem: 'Poor posture that makes every other move harder.',
    skillLevel: 'beginner', physDifficulty: 1, locations: ['home', 'hotel', 'office'],
    equipmentRequired: ['none'], equipmentOptional: ['clubs'], durationMin: 5,
    setup: 'Set up in front of a full-length mirror, face-on.',
    steps: ['Check: soft knees, tilt from the hips, straight spine.', 'Turn to a down-the-line view and check again.', 'Step away and rebuild it from scratch each rep.'],
    cues: ['Tilt from the hips, not the waist', 'Weight in the balls of your feet', 'Arms hang naturally under shoulders'],
    feel: 'An athletic, ready-to-move posture with a long spine.',
    mistakes: ['Rounding the lower back', 'Reaching for the ball'],
    easier: 'Face-on view only.', harder: 'Rebuild with eyes closed, then verify.',
    bodyAreas: ['lowerBack', 'hips', 'core'], golfSkills: ['setup', 'posture'], thumbnail: IMG.tempo,
    scoring: { unit: 'of 10', target: 8, better: 'higher', prompt: 'How many setups looked athletic?' },
    tags: ['home', 'no ball'], frequency: 'Daily is fine',
  }),
  mk({
    id: 'threeball', title: '9-Shot Shaping', summary: 'The ultimate control drill: three heights times three curves.',
    type: 'drill', category: 'Shot shaping', subcategory: 'Control', goals: ['striking', 'courseMgmt', 'tournament'],
    problem: 'No command over face and path when the course demands it.',
    skillLevel: 'advanced', physDifficulty: 2, locations: ['range'],
    equipmentRequired: ['clubs', 'balls'], durationMin: 15,
    setup: 'Hit low, medium, high with a straight ball first.',
    steps: ['Add a draw at each height.', 'Add a fade at each height.', 'Call your shot out loud before every swing.'],
    cues: ['Face controls start, path controls curve', 'Commit to the shape fully', 'Reset between each attempt'],
    feel: 'Deliberate face and path changes producing the called shape.',
    mistakes: ['Steering instead of committing', 'Rushing between shots'],
    easier: 'Just three heights, straight ball.', harder: 'Random shape called by a partner.',
    bodyAreas: ['core'], golfSkills: ['shot shaping'], thumbnail: IMG.drive,
    scoring: { unit: 'of 9', target: 5, better: 'higher', prompt: 'How many shapes came off?' },
    tags: ['advanced', 'control'], frequency: 'Occasionally, when sharp',
  }),
];

// ─── Golf-body: mobility, strength, power, balance ──────────────────────────

const fitness: Activity[] = [
  mk({
    id: 'mob-9090', title: '90/90 Hip Switches', summary: 'Free up the hip rotation your golf swing depends on.',
    type: 'mobility', category: 'Hips', subcategory: 'Rotation', goals: ['generalFitness', 'swingSpeed', 'striking'],
    problem: 'Tight hips that limit turn and force the low back to compensate.',
    skillLevel: 'all', physDifficulty: 1, locations: ['home', 'gym', 'hotel', 'outdoor'],
    equipmentRequired: ['none'], equipmentOptional: ['yogaMat'], durationMin: 5,
    reps: '8 per side', sets: 2, restSec: 20,
    setup: 'Sit on the floor, both knees bent at 90°, one shin in front, one out to the side.',
    steps: ['Keeping your chest tall, rotate both knees to the opposite side.', 'Let them settle to the floor, then switch back.', 'Move slowly and only as far as comfortable.'],
    cues: ['Sit tall, don’t collapse', 'Drive from the hips', 'Breathe through the stretch'],
    feel: 'A gentle stretch deep in the hips as they rotate.',
    mistakes: ['Rounding the back to reach further', 'Rushing the switches'],
    safety: 'Keep it pain-free. Stop if you feel sharp hip or back pain.',
    easier: 'Assist with your hands and reduce range.', harder: 'Pause 2 seconds at the end of each side.',
    bodyAreas: ['hips', 'glutes'], tags: ['mobility', 'warmup-friendly'], frequency: 'Daily or before golf',
  }),
  mk({
    id: 'mob-tspine', title: 'Open Book Thoracic Rotation', summary: 'Unlock upper-back rotation for a bigger, freer turn.',
    type: 'mobility', category: 'Thoracic spine', subcategory: 'Rotation', goals: ['generalFitness', 'swingSpeed', 'straighter'],
    problem: 'A stiff upper back that steals shoulder turn and adds strain.',
    skillLevel: 'all', physDifficulty: 1, locations: ['home', 'gym', 'hotel'],
    equipmentRequired: ['none'], equipmentOptional: ['yogaMat'], durationMin: 5,
    reps: '8 per side', sets: 2, restSec: 15,
    setup: 'Lie on your side, knees bent 90°, arms stacked out in front.',
    steps: ['Keeping knees down, sweep the top arm up and over like opening a book.', 'Follow your hand with your eyes and let the chest open to the ceiling.', 'Return slowly and repeat, then switch sides.'],
    cues: ['Rotate from the mid-back', 'Keep the knees pinned down', 'Reach long through the fingertips'],
    feel: 'The chest and upper back opening, not the lower back twisting.',
    mistakes: ['Letting the knees lift', 'Forcing the range'],
    easier: 'Smaller range, hand slides along the floor.', harder: 'Hold the open position for 3 breaths.',
    bodyAreas: ['tSpine', 'shoulders', 'upperBack'], tags: ['mobility'], frequency: 'Daily or before golf',
  }),
  mk({
    id: 'mob-shoulder', title: 'Shoulder CARs', summary: 'Controlled shoulder circles to keep the swing joint healthy.',
    type: 'mobility', category: 'Shoulders', subcategory: 'Controlled rotation', goals: ['generalFitness', 'straighter'],
    problem: 'Restricted, achy shoulders that limit backswing and follow-through.',
    skillLevel: 'all', physDifficulty: 1, locations: ['home', 'gym', 'office', 'hotel'],
    equipmentRequired: ['none'], durationMin: 4, reps: '5 per side', sets: 1,
    setup: 'Stand tall, one arm at your side.',
    steps: ['Slowly trace the biggest circle you can with your arm.', 'Move through full range with control, no momentum.', 'Reverse direction, then switch arms.'],
    cues: ['Go slow and deliberate', 'Keep the rest of the body still', 'Own every position'],
    feel: 'Smooth, controlled movement through the whole shoulder circle.',
    mistakes: ['Using momentum to swing', 'Shrugging or arching the back'],
    safety: 'Reduce range around any pinch; do not push into pain.',
    easier: 'Smaller circles.', harder: 'Add a light band for gentle resistance.',
    bodyAreas: ['shoulders', 'upperBack'], tags: ['mobility', 'desk-friendly'], frequency: 'Daily',
  }),
  mk({
    id: 'mob-ankle', title: 'Ankle Rocks', summary: 'Restore ankle bend for a stable, grounded swing.',
    type: 'mobility', category: 'Ankles', subcategory: 'Dorsiflexion', goals: ['generalFitness', 'striking'],
    problem: 'Stiff ankles that leak stability and rob the swing of ground force.',
    skillLevel: 'all', physDifficulty: 1, locations: ['home', 'gym', 'hotel', 'outdoor'],
    equipmentRequired: ['none'], durationMin: 4, reps: '10 per side', sets: 2, restSec: 15,
    setup: 'Half-kneel with one foot flat in front of you.',
    steps: ['Drive the front knee forward over the toes, heel down.', 'Rock gently back and forth through a comfortable range.', 'Switch sides.'],
    cues: ['Keep the heel planted', 'Knee tracks over the middle toes', 'Small, smooth rocks'],
    feel: 'A stretch through the front of the ankle and calf.',
    mistakes: ['Heel lifting off the floor', 'Knee caving inward'],
    easier: 'Standing, hands on a wall.', harder: 'Pause 2 seconds at end range each rep.',
    bodyAreas: ['ankles', 'legs'], tags: ['mobility'], frequency: '3–4× per week',
  }),
  mk({
    id: 'str-deadbug', title: 'Dead Bug', summary: 'Anti-extension core control that protects the low back.',
    type: 'strength', category: 'Core', subcategory: 'Anti-extension', goals: ['generalFitness', 'striking', 'distance'],
    problem: 'A soft, unstable core that lets the low back take the load.',
    skillLevel: 'beginner', physDifficulty: 2, locations: ['home', 'gym', 'hotel'],
    equipmentRequired: ['none'], equipmentOptional: ['yogaMat'], durationMin: 6,
    reps: '8 per side', sets: 3, restSec: 45,
    setup: 'Lie on your back, arms reaching to the ceiling, knees stacked over hips.',
    steps: ['Press your low back gently into the floor.', 'Slowly lower the opposite arm and leg toward the floor.', 'Return under control and switch sides.'],
    cues: ['Ribs down, low back flat', 'Move slowly', 'Exhale as you extend'],
    feel: 'The deep core working to keep your back still.',
    mistakes: ['Low back arching off the floor', 'Rushing the reps'],
    safety: 'Keep the back flat — if it arches, use a smaller range.',
    easier: 'Move only the legs, arms stay up.', harder: 'Add a light weight in each hand.',
    bodyAreas: ['core', 'lowerBack'], tags: ['strength', 'core'], frequency: '2–3× per week',
  }),
  mk({
    id: 'str-glutebridge', title: 'Glute Bridge', summary: 'Wake up the glutes that power hip drive and protect the back.',
    type: 'strength', category: 'Glutes', subcategory: 'Hip extension', goals: ['generalFitness', 'distance', 'swingSpeed'],
    problem: 'Weak, sleepy glutes that cap power and stress the low back.',
    skillLevel: 'beginner', physDifficulty: 2, locations: ['home', 'gym', 'hotel'],
    equipmentRequired: ['none'], equipmentOptional: ['yogaMat', 'bands'], durationMin: 6,
    reps: 12, sets: 3, restSec: 45,
    setup: 'Lie on your back, knees bent, feet flat and hip-width.',
    steps: ['Press through your heels and lift the hips.', 'Squeeze the glutes hard at the top for a second.', 'Lower slowly and repeat.'],
    cues: ['Squeeze the glutes, not the back', 'Ribs stay down', 'Push through the heels'],
    feel: 'The glutes doing the lifting, not the lower back.',
    mistakes: ['Arching the low back at the top', 'Pushing through the toes'],
    easier: 'Shorter range, both feet.', harder: 'Single-leg, or add a band around the knees.',
    bodyAreas: ['glutes', 'hips', 'core'], tags: ['strength'], frequency: '2–3× per week',
  }),
  mk({
    id: 'str-pallof', title: 'Band Pallof Press', summary: 'Anti-rotation strength — the brace that keeps your swing centred.',
    type: 'strength', category: 'Core', subcategory: 'Anti-rotation', goals: ['striking', 'straighter', 'swingSpeed'],
    problem: 'Losing posture and centre as the body rotates through the swing.',
    skillLevel: 'intermediate', physDifficulty: 3, locations: ['home', 'gym'],
    equipmentRequired: ['bands'], equipmentOptional: ['cable'], durationMin: 7,
    reps: '10 per side', sets: 3, restSec: 45,
    setup: 'Anchor a band at chest height; stand side-on, hands clasped at your chest.',
    steps: ['Press the band straight out from your chest.', 'Resist the pull that tries to rotate you.', 'Return slowly, keep the hips and chest square.'],
    cues: ['Don’t let the band twist you', 'Brace the core', 'Slow out, slow back'],
    feel: 'The core firing hard to stop your torso from turning.',
    mistakes: ['Letting the shoulders rotate', 'Holding your breath'],
    safety: 'Choose a band tension you can control without straining.',
    easier: 'Lighter band, shorter press.', harder: 'Add a pause at full extension.',
    bodyAreas: ['core', 'shoulders'], tags: ['strength', 'anti-rotation'], frequency: '2× per week',
  }),
  mk({
    id: 'str-splitsquat', title: 'Split Squat', summary: 'Single-leg strength for a stable base and better weight transfer.',
    type: 'strength', category: 'Legs', subcategory: 'Single leg', goals: ['generalFitness', 'distance', 'striking'],
    problem: 'Wobbly lower-body base and poor weight transfer in the swing.',
    skillLevel: 'intermediate', physDifficulty: 3, locations: ['home', 'gym', 'hotel'],
    equipmentRequired: ['none'], equipmentOptional: ['dumbbells'], durationMin: 8,
    reps: '8 per side', sets: 3, restSec: 60,
    setup: 'Stand in a split stance, one foot forward, one back on the toes.',
    steps: ['Lower straight down until the back knee nearly touches.', 'Keep the front shin fairly vertical.', 'Drive up through the front heel; switch sides after your reps.'],
    cues: ['Torso tall', 'Weight in the front heel', 'Control the descent'],
    feel: 'The front-leg glute and thigh working through a controlled range.',
    mistakes: ['Front knee caving in', 'Leaning too far forward'],
    safety: 'Hold a wall for balance if needed; avoid if kneeling aggravates a knee.',
    easier: 'Hold support, smaller range.', harder: 'Hold dumbbells or elevate the back foot.',
    bodyAreas: ['legs', 'glutes', 'core'], tags: ['strength', 'single-leg'], frequency: '2× per week',
  }),
  mk({
    id: 'pow-mbthrow', title: 'Rotational Med-Ball Throw', summary: 'Express swing-like rotational power — for players ready for it.',
    type: 'power', category: 'Rotational power', subcategory: 'Throw', goals: ['swingSpeed', 'distance'],
    problem: 'Rotational strength that never turns into swing speed.',
    skillLevel: 'advanced', physDifficulty: 4, locations: ['gym', 'outdoor'],
    equipmentRequired: ['medBall'], durationMin: 8,
    reps: '5 per side', sets: 3, restSec: 60,
    setup: 'Stand side-on to a sturdy wall, med ball at your trail hip.',
    steps: ['Coil into the trail side, then explosively rotate and throw the ball into the wall.', 'Catch or retrieve, reset your posture, and repeat.', 'Switch sides after your reps.'],
    cues: ['Drive from the ground up', 'Throw with the hips, not just the arms', 'Full commitment each rep'],
    feel: 'Ground-up rotation snapping through the hips and core.',
    mistakes: ['Throwing with only the arms', 'Skipping a proper warmup'],
    safety: 'Only for well-warmed, healthy backs. Skip if you have any current back or shoulder pain and see a professional if unsure.',
    easier: 'Lighter ball, sub-maximal effort.', harder: 'Heavier ball or add a step.',
    bodyAreas: ['core', 'hips', 'shoulders'], tags: ['power', 'advanced'], frequency: '1–2× per week when fresh',
  }),
  mk({
    id: 'bal-singleleg', title: 'Single-Leg Reach', summary: 'Balance and control for a steadier, more repeatable swing.',
    type: 'balance', category: 'Balance', subcategory: 'Single leg', goals: ['generalFitness', 'striking', 'confidence'],
    problem: 'Losing balance through the swing and into the finish.',
    skillLevel: 'beginner', physDifficulty: 2, locations: ['home', 'gym', 'office', 'hotel', 'outdoor'],
    equipmentRequired: ['none'], durationMin: 5, reps: '6 per side', sets: 2, restSec: 30,
    setup: 'Stand tall on one leg, soft knee.',
    steps: ['Hinge at the hips and reach the free foot behind you.', 'Reach as far as you can stay balanced, then return tall.', 'Complete your reps, then switch legs.'],
    cues: ['Long spine as you hinge', 'Slow and controlled', 'Fix your eyes on one spot'],
    feel: 'The standing-leg foot, ankle, and hip working to keep you steady.',
    mistakes: ['Rushing and losing form', 'Rounding the back'],
    easier: 'Fingertips on a wall.', harder: 'Close your eyes or stand on a cushion.',
    bodyAreas: ['ankles', 'hips', 'glutes', 'core'], tags: ['balance'], frequency: '3× per week',
  }),
];

// ─── Recovery pillars: yoga, stretch, warmup, recovery ──────────────────────

const recovery: Activity[] = [
  mk({
    id: 'yoga-hipflow', title: 'Golf Hip Yoga Flow', summary: 'A gentle flow to open the hips that power your turn.',
    type: 'yoga', category: 'Yoga', subcategory: 'Hip mobility', goals: ['generalFitness', 'swingSpeed'],
    problem: 'Tight hips and a body that feels locked up before or after golf.',
    skillLevel: 'all', physDifficulty: 1, locations: ['home', 'hotel', 'outdoor'],
    equipmentRequired: ['yogaMat'], equipmentOptional: ['none'], durationMin: 12,
    setup: 'Find a quiet space with room to move on a mat.',
    steps: ['Move through low lunge, both sides, breathing into the hips.', 'Flow to pigeon or a seated figure-four, holding a few breaths.', 'Finish in a gentle seated twist, each side.'],
    cues: ['Let the breath lead the movement', 'Ease into each shape', 'Never force a stretch'],
    feel: 'A slow, breathing release through the hips and glutes.',
    mistakes: ['Holding the breath', 'Pushing into sharp discomfort'],
    safety: 'Back off any pose that pinches. This is not a substitute for care of a real injury.',
    easier: 'Shorten holds, use blocks or a cushion.', harder: 'Extend holds to 8–10 breaths.',
    bodyAreas: ['hips', 'glutes', 'lowerBack'], tags: ['yoga', 'recovery'], frequency: '2–3× per week',
  }),
  mk({
    id: 'yoga-preround', title: 'Pre-Round Flow', summary: 'A short, active flow to feel loose and ready on the first tee.',
    type: 'yoga', category: 'Yoga', subcategory: 'Pre round', goals: ['generalFitness', 'confidence'],
    problem: 'Stepping onto the first tee cold, stiff, and rushing.',
    skillLevel: 'all', physDifficulty: 1, locations: ['course', 'home', 'outdoor'],
    equipmentRequired: ['none'], durationMin: 8,
    setup: 'Stand tall with room to move your arms and rotate.',
    steps: ['Flow through standing side bends and gentle back extensions.', 'Add slow standing rotations, arms swinging with the turn.', 'Finish with a few deep breaths and easy half-swings.'],
    cues: ['Keep it active, not deep', 'Build gradually', 'Breathe and relax the shoulders'],
    feel: 'Warm and mobile, not stretched-out and sleepy.',
    mistakes: ['Holding long deep stretches before playing', 'Skipping the breathing'],
    easier: 'Fewer rotations, smaller range.', harder: 'Add balance holds between shapes.',
    bodyAreas: ['fullBody', 'tSpine', 'hips'], tags: ['yoga', 'pre-round'], frequency: 'Before every round',
  }),
  mk({
    id: 'stretch-5min', title: 'Five-Minute Golf Stretch', summary: 'A quick full-body stretch for the areas golf tightens most.',
    type: 'stretch', category: 'Stretch', subcategory: 'Full body', goals: ['generalFitness'],
    problem: 'General tightness with only a few minutes to spare.',
    skillLevel: 'all', physDifficulty: 1, locations: ['home', 'office', 'hotel', 'course'],
    equipmentRequired: ['none'], durationMin: 5,
    setup: 'Stand with space to reach and rotate.',
    steps: ['Standing forward fold for the hamstrings and back, 30 seconds.', 'Cross-body shoulder stretch, each side, 20 seconds.', 'Standing quad and a gentle standing twist, each side.'],
    cues: ['Ease to a mild stretch, not pain', 'Breathe slowly', 'Relax into each hold'],
    feel: 'A mild, comfortable stretch that eases tension.',
    mistakes: ['Bouncing', 'Pushing to the point of pain'],
    safety: 'Keep every stretch gentle and pain-free.',
    easier: 'Support yourself and reduce range.', harder: 'Hold each stretch for 45 seconds.',
    bodyAreas: ['hamstrings', 'shoulders', 'lowerBack', 'legs'], tags: ['stretch', 'quick'], frequency: 'Daily or as needed',
  }),
  mk({
    id: 'stretch-postround', title: 'Post-Round Stretch', summary: 'Unwind after 18 holes and help your body recover.',
    type: 'stretch', category: 'Stretch', subcategory: 'Post round', goals: ['generalFitness'],
    problem: 'Stiffness and soreness settling in after a long round.',
    skillLevel: 'all', physDifficulty: 1, locations: ['course', 'home', 'outdoor'],
    equipmentRequired: ['none'], equipmentOptional: ['yogaMat'], durationMin: 8,
    setup: 'Find a calm spot to slow down and breathe.',
    steps: ['Gentle standing back extension and side bends.', 'Seated or standing hamstring and hip-flexor stretches.', 'Slow shoulder and neck stretches to finish.'],
    cues: ['Longer, relaxed holds', 'Deep, slow breathing', 'Let the tension melt'],
    feel: 'A calming release across the back, hips, and shoulders.',
    mistakes: ['Skipping it while you cool down', 'Rushing the holds'],
    safety: 'Sharp or lingering pain means rest and, if it persists, see a professional.',
    easier: 'Fewer stretches, supported.', harder: 'Add foam rolling before you stretch.',
    bodyAreas: ['lowerBack', 'hips', 'hamstrings', 'shoulders', 'neck'], tags: ['stretch', 'post-round'], frequency: 'After every round',
  }),
  mk({
    id: 'warm-5min', title: 'Five-Minute Pre-Round Warmup', summary: 'The minimum effective warmup to play loose from hole one.',
    type: 'warmup', category: 'Warmup', subcategory: 'Pre round', goals: ['generalFitness', 'confidence', 'tournament'],
    problem: 'Starting rounds cold and taking six holes to feel loose.',
    skillLevel: 'all', physDifficulty: 2, locations: ['course', 'range', 'outdoor'],
    equipmentRequired: ['none'], equipmentOptional: ['clubs'], durationMin: 5,
    setup: 'Give yourself space near the first tee or range.',
    steps: ['Leg swings and hip circles to wake up the lower body.', 'Standing trunk rotations, building range gradually.', 'A club behind the shoulders, easy turns, then a few half-swings.'],
    cues: ['Build from small to full', 'Raise the heart rate a little', 'Finish feeling springy'],
    feel: 'Warm, mobile, and ready — not fatigued.',
    mistakes: ['Long static stretching instead of movement', 'Going straight to full swings'],
    safety: 'Ease into rotations, especially in cold weather.',
    easier: 'Movements only, no club.', harder: 'Add the ten-minute version with a wedge ladder.',
    bodyAreas: ['fullBody', 'hips', 'tSpine'], tags: ['warmup', 'pre-round'], frequency: 'Before every round',
  }),
  mk({
    id: 'warm-range', title: 'Driving Range Warmup', summary: 'Warm up your body and your swing before you smash drivers.',
    type: 'warmup', category: 'Warmup', subcategory: 'Range', goals: ['striking', 'generalFitness'],
    problem: 'Grabbing the driver first and grooving bad habits cold.',
    skillLevel: 'all', physDifficulty: 2, locations: ['range'],
    equipmentRequired: ['clubs', 'balls'], durationMin: 10,
    setup: 'Start at the range with a wedge, not the driver.',
    steps: ['Two minutes of leg swings, trunk rotations, and arm circles.', 'Half-swing wedges, then work up through the bag a few balls each.', 'Finish with a handful of drivers at smooth, building effort.'],
    cues: ['Body first, then swing', 'Short clubs to long', 'Rhythm over power early'],
    feel: 'A gradual build to full speed with a warm, loose body.',
    mistakes: ['Starting with the driver', 'Raking and hitting with no purpose'],
    safety: 'In cold weather, spend longer on the movement warmup.',
    easier: 'Wedges and mid-irons only.', harder: 'Add a shot-shaping ladder before driver.',
    bodyAreas: ['fullBody'], tags: ['warmup', 'range'], frequency: 'Before every range session',
  }),
  mk({
    id: 'rec-foamroll', title: 'Golfer’s Foam Roll Flow', summary: 'Roll out the areas golf loads most to aid recovery.',
    type: 'recovery', category: 'Recovery', subcategory: 'Foam rolling', goals: ['generalFitness'],
    problem: 'Persistent tightness in the back, hips, and legs after golf.',
    skillLevel: 'all', physDifficulty: 1, locations: ['home', 'gym', 'hotel'],
    equipmentRequired: ['foamRoller'], equipmentOptional: ['yogaMat'], durationMin: 8,
    setup: 'Lie on a mat with the foam roller to hand.',
    steps: ['Roll the upper back (mid-back only), slow passes.', 'Roll the glutes and the sides of the thighs.', 'Finish on the calves; pause on tender spots and breathe.'],
    cues: ['Roll slowly', 'Avoid the low back and joints', 'Breathe on tender spots'],
    feel: 'A tolerable "good ache" that eases as tissue relaxes.',
    mistakes: ['Rolling directly on the low back', 'Rushing over tight spots'],
    safety: 'Never roll over the lower back or bony joints. Keep pressure tolerable.',
    easier: 'Less pressure, fewer areas.', harder: 'Add gentle mobility between areas.',
    bodyAreas: ['upperBack', 'glutes', 'legs'], tags: ['recovery', 'foam-rolling'], frequency: 'After hard sessions or rounds',
  }),
  mk({
    id: 'rec-postround', title: 'Post-Round Recovery', summary: 'A gentle cool-down to bounce back for tomorrow.',
    type: 'recovery', category: 'Recovery', subcategory: 'Post round', goals: ['generalFitness'],
    problem: 'Feeling wrecked the day after a round.',
    skillLevel: 'all', physDifficulty: 1, locations: ['home', 'hotel', 'course'],
    equipmentRequired: ['none'], equipmentOptional: ['foamRoller', 'yogaMat'], durationMin: 10,
    setup: 'Somewhere calm to move slowly and breathe.',
    steps: ['A short, easy walk or gentle marching to keep blood moving.', 'Light hip and back mobility, small ranges.', 'Slow breathing for two minutes to down-regulate.'],
    cues: ['Keep everything gentle', 'Move, don’t stretch hard', 'Slow the breath right down'],
    feel: 'Calm, loose, and recovering — nothing strenuous.',
    mistakes: ['Doing an intense workout when already fatigued', 'Sitting straight down with no movement'],
    safety: 'If something hurts beyond normal soreness, rest and seek advice.',
    easier: 'Breathing and a short walk only.', harder: 'Add the foam-roll flow first.',
    bodyAreas: ['fullBody', 'hips', 'lowerBack'], tags: ['recovery', 'post-round'], frequency: 'After every round',
  }),
];

// ─── Public API ─────────────────────────────────────────────────────────────

export const ACTIVITIES: Activity[] = [...skillDrills, ...fitness, ...recovery];

export const activityById = (id: string): Activity | undefined => ACTIVITIES.find((a) => a.id === id);
